[package]
name = "gcd"
version = "0.1.0"
authors=["2579470956@qq.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web="4.1"
serde={version = "1.0",features = ["derive"]}
